#config_version=5


##! mode: skill_shot
mode:
  start_events: start_skillshot
  stop_events:
    - skill_success
    - skill_failed
#     - s_left_jet_active
#    - s_bottom_jet_active
#    - s_right_jet_active
#    - s_bottom_popper_active
 #   - s_right_drop_lock_front_active
  #  - s_right_drop_lock_back_active
   # - s_t5_active
    #- s_t6_active
    #- s_t7_active
  events_when_stopped: start_base
    
  priority: 500
shots:
  skill_q:
    switch: s_q
    profile: skill_shot_profile
    advance_events: mode_skillshot_started        # replace "skill_shot" with your mode name
    show_tokens:
      light: 0_led116
  skill_w:
    switch: s_w
    profile: skill_shot_profile
    show_tokens:
      light: 0_led117
  skill_e:
    switch: s_e
    profile: skill_shot_profile
    show_tokens:
      light: 0_led118
  skill_r:
    switch: s_r
    profile: skill_shot_profile
    show_tokens:
      light: 0_led119
shot_groups:
  skill_shot:
    shots: skill_q, skill_w, skill_e, skill_r
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active
    disable_rotation_events: s_plunger_inactive
    
shot_profiles:
  skill_shot_profile:
    states:
      - name: unlit
        show: off
      - name: flashing
        show: flash_color
        show_tokens:
          color: teal
        speed: 4

    loop: true
variable_player:
  skill_success:
    score: 250000
timers:
  skill_shot_timeout:
    start_value: 0
    end_value: 5    # set the timeout of your skill shot here
    direction: up
    tick_interval: 1
    start_running: false
    control_events:
      - action: start
        event: balldevice_bd_plunger_ball_eject_success  # replace "plunger_lane" with the name of your plunger device
state_machines:
  skill_shot_success:
    debug: true
    states:
      start:
        label: Skill shot ready
      success:
        label: Skill successful
        events_when_started: skill_success
      failed:
        label: Skill failed
        events_when_started: skill_failed, ss_failed
    transitions:
      - source: start
        target: success
        events: skill_shot_flashing_hit
      - source: start
        target: failed
        events: skill_shot_unlit_hit, timer_skill_shot_timeout_complete

show_player: 

  mode_skillshot_started: 

    skillshot_show: 
      priority: 900
      speed: 4
    backwall4:
      priority: 900
      speed: 4    


    
