#config_version=5


##! mode: ball_save
mode:
  start_events: ball_started
  stop_events: ball_save_show_ended
  events_when_stopped: start_zombie_bs

ball_saves:
  ball_save_ball_save:
    active_time: 10s
    hurry_up_time: 5s
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    auto_launch: true
    balls_to_save: 1
    early_ball_save_events: s_right_outlane_active, s_ball_save_active
    
  random_ball_save:
    active_time: 5s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: event_on_dangerous_action
    auto_launch: true
    balls_to_save: 1   
     
show_player:
  ball_save_ball_save_ball_save_timer_start:
    flash_color:
      key: ball_save
      speed: 2
      show_tokens:
        lights: 0_led0
        color: yellow
  ball_save_ball_save_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 6
      show_tokens:
        lights: 0_led0
        color: red
  ball_save_ball_save_ball_save_disabled:
    ball_save: stop
    
  ball_save_ball_save_ball_save_saving_ball:
    ball_save_show:
      priority: 900
      speed: 13
      loops: 2    

    bs_video:
      priority: 900
      speed: 13
      loops: 0    

    
