#config_version=5
##! mode: top_lanes
mode:
  start_events: mode_skillshot_stopped 
  priority: 600
  stop_events: stop_mode_top_lanes, ball_will_end, ball_ended, smdr_group_hit_complete

shots:
  left_pop_bumper:
    switch: s_left_jet
    profile: top_lane_profile
    show_tokens:
      led: 0_led116
      color: pink

  right_pop_bumper:
    switch: s_right_jet
    profile: top_lane_profile
    show_tokens:
      led: 0_led117
      color: pink
      
  center_pop_bumper:
    switch: s_bottom_jet
    profile: top_lane_profile  
    show_tokens:
      led: 0_led118
      color: pink


shot_groups:
  top_lane_group:
    shots: top_lane_q, top_lane_w, top_lane_e, top_lane_r
    reset_events: top_lane_group_hit_complete, ball_will_end


shot_profiles:
  top_lane_profile:
    states:
      - name:
        show: off
      - name: hit
        show: lighton

variable_player:
  top_lane_group_hit_complete:
    score: 500000
    bonus_multiplier: 2
  s_q_active:
    score: 10000
  s_w_active:
    score: 10000
  s_e_active:
    score: 10000
  s_r_active:
    score: 10000
    
    
show_player:

  top_lane_group_hit_complete:
    light_blink:
      action: play
      loops: 4
      speed: 10
      priority: 701
      show_tokens:
        led: 0_led116,0_led117,0_led118, 0_led119          
        color: teal
    toplane_show: 
      speed: 20
      loops: 0


