#config_version=5

mode:
  start_events: ball_starting
  priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        y: 200
        x: left
        anchor_x: left
        anchor_y: top
        font_size: 50
        text: Teemo's Shrooms - (Shrooms)

variable_player:
  s_drop_front_active:
    score: 1000
  s_drop_middle_active:
    score: 1000
  s_drop_back_active:
    score: 1000
  s_bottom_jet_active:
    score: 1000
    Shrooms: 1
  s_left_jet_active:
    score: 1000
    Shrooms: 1
  s_right_jet_active:
    score: 1000
    Shrooms: 1

shows:
  rainbow:
    - lights:
        (leds): red
    - lights:
        (leds): orange
    - lights:
        (leds): yellow
    - lights:
        (leds): green
    - lights:
        (leds): blue
    - lights:
        (leds): purple
      duration: 3s

show_player:
  play_rainbow_show_on_targets:
    rainbow:
      show_tokens:
        leds: led1, led2, led3, led4, led5, led6, led7, led8, led9