#config_version=5

mode:
  start_events: start_base
  stop_events: game_ended, service_mode_entered
  priority: 600

#!Base Slide_player

slide_player: 

     
  single_player_ball_starting:
    base_slide_main:
      target: display2
      action: play
    base_slide_mini:
      target: display3
      action: play

  multi_player_ball_started:
    base_slide_main_4p:
      target: display2
      action: play
    base_slide_mini:
      target: display3
      action: play

  multiplayer_game{'<Player 2>'}:
    base_slide_main:
      action: remove
    base_slide_main_2p:
      target: display2
      action: play

  multiplayer_game{'<Player 2>' and '<Player 3>'}:
    base_slide_main_2p:
      action: remove
    base_slide_main_3p:
      target: display2
      action: play

  multiplayer_game{'<Player 2>' and '<Player 3>' and '<Player 4>'}:
    base_slide_main_3p:
      action: remove
    base_slide_main_4p:
      target: display2
      action: play
      
widgets: 

  garen: 
    type: image
    image: smallgaren 
    x: center - 200 
    y: center - 450

       
  jinx: 
    type: image
    image: smalljinx  
    x: center - 200 
    y: center - 450 
        
  vi: 
    type: image
    image: smallvi     
    x: center - 200 
    y: center - 450 
                   
  thresh: 
    type: image
    image: smallthresh    
    x: center - 200 
    y: center - 450
          
slides: 

  base_slide_main:
    # priority: 5000
     widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 300
        x: center
        y: center
        color: gold

      #- type: rectangle
      #  x: center
       # y: center
       # width: 1500
       # height: 300
       # color: black
       # opacity: .75
      - type: text
        text: PLAYER (number)
        color: white
        y: 60
        x: center + 80
        font_size: 80
        anchor_x: center
        anchor_y: bottom
        
      - type: text
        text: (ball)
        color: white
        y: 55
        x: center - 195
        anchor_x: center
        anchor_y: bottom
        font_size: 80
        
      - widget: (current_player.selected_champ)
        height: 50
        width: 50

      - type: image
        image: singlescore
        x: center
        y: center - 40

      - type: image
        image: dmdborder
        x: center -10
        y: center - 30        
      - type: image
        image: scorebg3
        x: center
        y: center - 50

        



  base_slide_main_2p:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 300
        x: center
        y: center
        color: gold

      #- type: rectangle
      #  x: center
       # y: center
       # width: 1500
       # height: 300
       # color: black
       # opacity: .75
      - type: text
        text: PLAYER (number)
        color: white
        y: 60
        x: center + 80
        font_size: 80
        anchor_x: center
        anchor_y: bottom
        
      - type: text
        text: (ball)
        color: white
        y: 55
        x: center - 195
        anchor_x: center
        anchor_y: bottom
        font_size: 80
        
        
      - widget: (current_player.selected_champ)
        height: 50
        width: 50



      - type: text
        text: (player1|score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: left + 250
        y: top - 110

      - type: text
        text: (player2|score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: right - 250 
        y: top - 110


      - type: text
        text: (player3|score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: left + 250 
        y: bottom - 80
        
  
      - widget: (current_player.selected_champ)
        height: 50
        width: 50

      - type: image
        image: singlescore
        x: center
        y: center - 40

      - type: image
        image: dmdborder
        x: center -10
        y: center - 30        
      - type: image
        image: scorebg3
        x: center
        y: center - 50

  base_slide_main_3p:
    widgets:  
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 300
        x: center
        y: center
        color: gold

      #- type: rectangle
      #  x: center
       # y: center
       # width: 1500
       # height: 300
       # color: black
       # opacity: .75
      - type: text
        text: PLAYER (number)
        color: white
        y: 60
        x: center + 80
        font_size: 80
        anchor_x: center
        anchor_y: bottom
        
      - type: text
        text: (ball)
        color: white
        y: 55
        x: center - 195
        anchor_x: center
        anchor_y: bottom
        font_size: 80
        
                
      - widget: (current_player.selected_champ)
        height: 50
        width: 50


      - type: text
        text: (player1|score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: left + 250
        y: top - 110

      - type: text
        text: (player2|score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: right - 250 
        y: top - 110


      - type: text
        text: (player3|score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: left + 250
        y: bottom + 250
        
      - type: image
        image: singlescore
        x: center
        y: center - 40

      - type: image
        image: dmdborder
        x: center -10
        y: center - 30        
      - type: image
        image: scorebg3
        x: center
        y: center - 50
        
  base_slide_main_4p:
    widgets:  
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 300
        x: center
        y: center
        color: gold

      #- type: rectangle
      #  x: center
       # y: center
       # width: 1500
       # height: 300
       # color: black
       # opacity: .75
      - type: text
        text: PLAYER (number)
        color: white
        y: 60
        x: center + 80
        font_size: 80
        anchor_x: center
        anchor_y: bottom
        
      - type: text
        text: (ball)
        color: white
        y: 55
        x: center - 195
        anchor_x: center
        anchor_y: bottom
        font_size: 80
        
        
      - widget: (current_player.selected_champ)
        height: 50
        width: 50
        
        
      - type: text
        text: (player1|score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: left + 250
        y: top - 110

      - type: text
        text: (player2|score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: right - 250 
        y: top - 110


      - type: text
        text: (player3|score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: left + 250
        y: bottom + 250

      - type: text
        text: (player4|score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: right - 250
        y: bottom + 250
        
      - type: image
        image: singlescore
        x: center
        y: center - 40

      - type: image
        image: dmdborder
        x: center -10
        y: center - 30        
      - type: image
        image: scorebg3
        x: center
        y: center - 50     

  base_slide_mini:
     priority: 1
     widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        x: center
        y: top - 100
      - type: text
        y: bottom
        x: left
        anchor_x: left - 50
        anchor_y: bottom
        font_size: 35
        text: Teemo's Shrooms - (Shrooms)
      - type: text
        y: bottom
        x: right - 150
        anchor_x: right + 50
        anchor_y: bottom
        font_size: 35
        text: CS - (CS)

coil_player:
  enable_shaker_event:
    c_shaker: enable
  disable_shaker_event:
    c_shaker: disable

variable_player:
  s_drop_front_active:
    score: 1000
  s_drop_middle_active:
    score: 1000
  s_drop_back_active:
    score: 1000
  s_bottom_jet_active:
    score: 5000
    Shrooms: 1
  s_left_jet_active:
    score: 5000
    Shrooms: 1
    c_shaker: enable
    
  s_right_jet_active:
    score: 5000
    Shrooms: 1
  s_right_slingshot_active:
    score: 1000
  s_left_slingshot_active:
    score: 1000

  s_t11_active:
    score: 10000
    CS: 1
  s_t12_active:
    score: 10000
    CS: 1
  s_t3_active:
    score: 5000
    CS: 1
  s_t4_active:
    score: 5000
    CS: 1  
  s_t5_active:
    score: 5000
    CS: 1
  s_t6_active:
    score: 5000
    CS: 1
  s_left_target_active:
    score: 5000
    CS: 1
  s_right_target_active:
    score: 5000
    CS: 1
  s_t7_active:
    score: 5000
    CS: 1
  s_t8_active:
    score: 5000
    CS: 1
  s_tward_active:
    score: 25000
    CS: 1

  s_right_ramp_active:
    score: 10000
    
  s_left_spinner_active:
    score: 1000
    
  s_right_spinner_active:
    score: 1000    


shows:
  rainbow:
    - lights:
        (leds): red
    - lights:
        (leds): orange
    - lights:
        (leds): yellow
    - lights:
        (leds): green
    - lights:
        (leds): blue
    - lights:
        (leds): purple
      duration: 3s

show_player:

  mode_base_started: 

    base_backglass:
      speed: 4

  s_tward_active:
    
    ward_light:
      speed: 4
event_player:

  mode_base_started: start_skillshot
  mode_base_started{game.num_players==1}: single_player_ball_starting
  mode_base_started{game.num_players==2}: multiplayer_game{'<Player 2>'} 
  mode_base_started{game.num_players==3}: multiplayer_game{'<Player 2>' and '<Player 3>'}
  mode_base_started{game.num_players==4}: multiplayer_game{'<Player 2>' and '<Player 3>' and '<Player 4>'} 
  
sound_player: 

  spinner_right_spinner_active:
    jinxr2:
      action: play
  
  spinner_left_spinner_active:
    jusitce:
      action: play 
      
  s_right_ramp_active:
    jinxr1:
      action: play
      
  s_left_ramp_active:
    kat3:
      action: play                
