#config_version=5


##! mode: right_orbit
mode:
  start_events: mode_skillshot_stopped
  stop_events:
    - orbit_success
    - ball_will_end
  priority: 600


show_player: 

  mode_right_orbit_started: 

    right_orbit_show: 
      priority: 900
      speed: 13



    