#config_version=5
##! mode: bottom_lanes                    
mode:
  start_events: mode_skillshot_stopped 
  priority: 600
  stop_events: stop_mode_bottom_lanes, ball_will_end, ball_ended, smdr_group_hit_complete

shots:
  bottom_lane_d:
    switch: s_left_inlane
    profile: bot_lane_profile
    show_tokens:
      led: 0_led13
      color: pink

  bottom_lane_f:
    switch: s_right_inlane
    profile: bot_lane_profile
    show_tokens:
      led: 0_led36
      color: pink
  bottom_lane_b:
    switch: s_right_outlane
    profile: bot_lane_profile  
    show_tokens:
      led: 0_led37
      color: pink



shot_groups:
  bot_lane_group:
    shots: bottom_lane_d, bottom_lane_f, bottom_lane_b
    reset_events: bot_lane_group_hit_complete, ball_will_end
    rotate_left_events: s_flipper_left_active
    rotate_right_events: s_flipper_right_active

shot_profiles:
  bot_lane_profile:
    states:
      - name:
        show: off
      - name: hit
        show: lighton

variable_player:
  bot_lane_group_hit_complete:
    score: 500000
    bonus_multiplier: 2
  s_left_inlane_active:
    score: 10000
  s_right_inlane_active:
    score: 10000
  s_right_outlane_active:
    score: 10000

    
    
show_player:

  bot_lane_group_hit_complete:
    light_blink:
      action: play
      loops: 4
      speed: 10
      priority: 701
      show_tokens:
        led: 0_led13,0_led36,0_led37         
        color: teal



