#config_version=5


##! mode: base_led
mode:
  start_events: ball_starting
  stop_events:
    - ball_ended
  priority: 100


show_player: 

  mode_base_led_started: 

    base_led_show: 
      priority: 100
      speed: 13
    backwall2: 
      priority: 100
      speed: 13
   #drop_show: 
     # priority: 60
     # speed: 13

    
