#config_version=5

lights:
   
    
  0_led0:
    number: 0-0-0
    tags: seq0
    type: grb
  0_led1:
    number: 0-0-1
    tags: seq1
    type: grb
  0_led2:
    number: 0-0-2
    tags: seq2
    type: grb
  0_led3:
    number: 0-0-3
    tags: seq3
    type: grb
  0_led4:
    number: 0-0-4
    tags: seq4
    type: grb
  0_led5:
    number: 0-0-5
    tags: seq5
    type: grb
  0_led6:
    number: 0-0-6
    tags: seq6
    type: grb
  0_led7:
    number: 0-0-7
    tags: seq7
    type: grb
  0_led8:
    number: 0-0-8
    tags: seq8
    type: grb
  0_led9:
    number: 0-0-9
    tags: seq9
    type: grb
    
   
  0_led10:
    number: 0-0-10
    tags: seq0
    type: grb
  0_led11:
    number: 0-0-11
    tags: seq1
    type: grb
  0_led12:
    number: 0-0-12
    tags: seq2
    type: grb
  0_led13:
    number: 0-0-13
    tags: seq3
    type: grb
  0_led14:
    number: 0-0-14
    tags: seq4
    type: grb
  0_led15:
    number: 0-0-15
    tags: seq5
    type: grb
  0_led16:
    number: 0-0-16
    tags: seq6
    type: grb
  0_led17:
    number: 0-0-17
    tags: seq7
    type: grb
  0_led18:
    number: 0-0-18
    tags: seq8
    type: grb
  0_led19:
    number: 0-0-19
    tags: seq9
    type: grb


  0_led20:
    number: 0-0-20
    tags: seq0
    type: grb
  0_led21:
    number: 0-0-21
    tags: seq1
    type: grb
  0_led22:
    number: 0-0-22
    tags: seq2
    type: grb
  0_led23:
    number: 0-0-23
    tags: seq3
    type: grb
  0_led24:
    number: 0-0-24
    tags: seq4
    type: grb
  0_led25:
    number: 0-0-25
    tags: seq5
    type: grb
  0_led26:
    number: 0-0-26
    tags: seq6
    type: grb
  0_led27:
    number: 0-0-27
    tags: seq7
    type: grb
  0_led28:
    number: 0-0-28
    tags: seq8
    type: grb
  0_led29:
    number: 0-0-29
    tags: seq9    
    type: grb   

  0_led30:
    number: 0-0-30
    tags: seq0
    type: grb
  0_led31:
    number: 0-0-31
    tags: seq1
    type: grb
  0_led32:
    number: 0-0-32
    tags: seq2
    type: grb
  0_led33:
    number: 0-0-33
    tags: seq3
    type: grb
  0_led34:
    number: 0-0-34
    tags: seq4
    type: grb
  0_led35:
    number: 0-0-35
    tags: seq5
    type: grb
  0_led36:
    number: 0-0-36
    tags: seq6
    type: grb
  0_led37:
    number: 0-0-37
    tags: seq7
    type: grb
  0_led38:
    number: 0-0-38
    tags: seq8
    type: grb
  0_led39:
    number: 0-0-39
    tags: seq9       
    type: grb
    

  0_led40:
    number: 0-0-40
    tags: seq0
    type: grb
  0_led41:
    number: 0-0-41
    tags: seq1
    type: grb
  0_led42:
    number: 0-0-42
    tags: seq2
    type: grb
  0_led43:
    number: 0-0-43
    tags: seq3
    type: grb
  0_led44:
    number: 0-0-44
    tags: seq4
    type: grb
  0_led45:
    number: 0-0-45
    tags: seq5
    type: grb
  0_led46:
    number: 0-0-46
    tags: seq6
    type: grb
  0_led47:
    number: 0-0-47
    tags: seq7
    type: grb
  0_led48:
    number: 0-0-48
    tags: seq8
    type: grb
  0_led49:
    number: 0-0-49
    tags: seq9
    type: grb     
  0_led50:
    number: 0-0-50
    tags: seq0
    type: grb
  0_led51:
    number: 0-0-51
    tags: seq1
    type: grb
  0_led52:
    number: 0-0-52
    tags: seq2
    type: grb
  0_led53:
    number: 0-0-53
    tags: seq3
    type: grb
  0_led54:
    number: 0-0-54
    tags: seq4
    type: grb
  0_led55:
    number: 0-0-55
    tags: seq5
    type: grb
  0_led56:
    number: 0-0-56
    tags: seq6
    type: grb
  0_led57:
    number: 0-0-57
    tags: seq7
    type: grb
  0_led58:
    number: 0-0-58
    tags: seq8
    type: grb
  0_led59:
    number: 0-0-59
    tags: seq9
    type: grb     
  0_led60:
    number: 0-0-60
    tags: seq0
    type: grb
  0_led61:
    number: 0-0-61
    tags: seq1
    type: grb
  0_led62:
    number: 0-0-62
    tags: seq2
    type: grb
  0_led63:
    number: 0-0-63
    tags: seq3
    type: grb
  0_led64:
    number: 0-0-64
    tags: seq4
    type: grb
  0_led65:
    number: 0-0-65
    tags: seq5
    type: grb
  0_led66:
    number: 0-0-66
    tags: seq6
    type: grb
  0_led67:
    number: 0-0-67
    tags: seq7
    type: grb
  0_led68:
    number: 0-0-68
    tags: seq8
    type: grb
  0_led69:
    number: 0-0-69
    tags: seq9
    type: grb     
  0_led70:
    number: 0-0-70
    tags: seq0
    type: grb
  0_led71:
    number: 0-0-71
    tags: seq1
    type: grb
  0_led72:
    number: 0-0-72
    tags: seq2
    type: rgb
  0_led73:
    number: 0-0-73
    tags: seq3
    type: rgb
  0_led74:
    number: 0-0-74
    tags: seq4
    type: rgb
  0_led75:
    number: 0-0-75
    tags: seq5
    type: rgb
  0_led76:
    number: 0-0-76
    tags: seq6
    type: rgb
  0_led77:
    number: 0-0-77
    tags: seq7
    type: rgb
  0_led78:
    number: 0-0-78
    tags: seq8
    type: rgb
  0_led79:
    number: 0-0-79
    tags: seq9
    type: rgb    
  0_led80:
    number: 0-0-80
    tags: seq0
    type: rgb
  0_led81:
    number: 0-0-81
    tags: seq1
    type: rgb
  0_led82:
    number: 0-0-82
    tags: seq2
    type: rgb
  0_led83:
    number: 0-0-83
    tags: seq3
    type: rgb
  0_led84:
    number: 0-0-84
    tags: seq4
    type: rgb
  0_led85:
    number: 0-0-85
    tags: seq5
    type: rgb
  0_led86:
    number: 0-0-86
    tags: seq6
    type: rgb
  0_led87:
    number: 0-0-87
    tags: seq7
    type: rgb
  0_led88:
    number: 0-0-88
    tags: seq8
    type: rgb
  0_led89:
    number: 0-0-89
    tags: seq9
    type: rgb     
  0_led90:
    number: 0-0-90
    tags: seq0
    type: rgb
  0_led91:
    number: 0-0-91
    tags: seq1
    type: rgb
  0_led92:
    number: 0-0-92
    tags: seq2
    type: rgb
  0_led93:
    number: 0-0-93
    tags: seq3
    type: rgb
  0_led94:
    number: 0-0-94
    tags: seq4
    type: rgb
  0_led95:
    number: 0-0-95
    tags: seq5
    type: rgb
  0_led96:
    number: 0-0-96
    tags: seq6
    type: rgb
  0_led97:
    number: 0-0-97
    tags: seq7
    type: rgb
  0_led98:
    number: 0-0-98
    tags: seq8
    type: grb
  0_led99:
    number: 0-0-99
    tags: seq9
    type: grb     
  0_led100:   
    number: 0-0-100
    tags: seq0
    type: grb
  0_led101:
    number: 0-0-101
    tags: seq1
    type: rgb
  0_led102:
    number: 0-0-102
    tags: seq2
    type: rgb
  0_led103:
    number: 0-0-103
    tags: seq3
    type: rgb
  0_led104:
    number: 0-0-104
    tags: seq4
    type: rgb
  0_led105:
    number: 0-0-105
    tags: seq5
    type: rgb
  0_led106:
    number: 0-0-106
    tags: seq6
    type: rgb
  0_led107:
    number: 0-0-107
    tags: seq7
    type: rgb
  0_led108:
    number: 0-0-108
    tags: seq8
    type: rgb
  0_led109:
    number: 0-0-109
    tags: seq9
    type: rgb  
  0_led110:   
    number: 0-0-110
    tags: seq0
    type: rgb
  0_led111:
    number: 0-0-111
    tags: seq1
    type: rgb
  0_led112:
    number: 0-0-112
    tags: seq2
    type: grb
  0_led113:
    number: 0-0-113
    tags: seq3
    type: grb
  0_led114:
    number: 0-0-114
    tags: seq4
    type: grb
  0_led115:
    number: 0-0-115
    tags: seq5
    type: grb
  0_led116:
    number: 0-0-116
    tags: seq6
    type: grb
  0_led117:
    number: 0-0-117
    tags: seq7
    type: grb
  0_led118:
    number: 0-0-118
    tags: seq8
    type: grb
  0_led119:
    number: 0-0-119
    tags: seq9
    type: grb      
  0_led120:   
    number: 0-0-120
    tags: seq0
    type: grb
  0_led121:
    number: 0-0-121
    tags: seq1
    type: grb
  0_led122:
    number: 0-0-122
    tags: seq2
    type: grb
  0_led123:
    number: 0-0-123
    tags: seq3
    type: grb
  0_led124:
    number: 0-0-124
    tags: seq4
    type: grb
  0_led125:
    number: 0-0-125
    tags: seq5
    type: grb
  0_led126:
    number: 0-0-126
    tags: seq6
    type: grb
  0_led127:
    number: 0-0-127
    tags: seq7
    type: grb
  0_led128:
    number: 0-0-128
    tags: seq8
    type: grb
  0_led129:
    number: 0-0-129
    tags: seq9
    type: grb    
  0_led130:   
    number: 0-0-130
    tags: seq0
    type: rgb
  0_led131:
    number: 0-0-131
    tags: seq1
    type: rgb
  0_led132:
    number: 0-0-132
    tags: seq2
    type: rgb
  0_led133:
    number: 0-0-133
    tags: seq3
    type: rgb
  0_led134:
    number: 0-0-134
    tags: seq4
    type: rgb
  0_led135:
    number: 0-0-135
    tags: seq5
    type: rgb
  0_led136:
    number: 0-0-136
    tags: seq6
    type: rgb
  0_led137:
    number: 0-0-137
    tags: seq7
    type: rgb
  0_led138:
    number: 0-0-138
    tags: seq8
    type: grb
  0_led139:
    number: 0-0-139
    tags: seq9
    type: grb   
  0_led140:   
    number: 0-0-140
    tags: seq0
    type: grb
  0_led141:
    number: 0-0-141
    tags: seq1
    type: grb
  0_led142:
    number: 0-0-142
    tags: seq2
    type: grb
  0_led143:
    number: 0-0-143
    tags: seq3
    type: grb
  0_led144:
    number: 0-0-144
    tags: seq4
    type: grb
  0_led145:
    number: 0-0-145
    tags: seq5
    type: grb
  0_led146:
    number: 0-0-146
    tags: seq6
    type: grb
  0_led147:
    number: 0-0-147
    tags: seq7
    type: grb
  0_led148:
    number: 0-0-148
    tags: seq8
    type: grb
  0_led149:
    number: 0-0-149
    tags: seq9
    type: grb   
  0_led150:   
    number: 0-0-150
    tags: seq0
    type: grb
  0_led151:
    number: 0-0-151
    tags: seq1
    type: grb
  0_led152:
    number: 0-0-152
    tags: seq2
    type: grb
  0_led153:
    number: 0-0-153
    tags: seq3
    type: grb
  0_led154:
    number: 0-0-154
    tags: seq4
    type: grb
  0_led155:
    number: 0-0-155
    tags: seq5
    type: grb
  0_led156:
    number: 0-0-156
    tags: seq6
    type: grb
  0_led157:
    number: 0-0-157
    tags: seq7
  0_led158:
    number: 0-0-158
    tags: seq8
  0_led159:
    number: 0-0-159
    tags: seq9   