#config_version=5


##! mode: ball_save
mode:
  start_events: ball_started
  stop_events: multiball_3balls_multiball_ended, player_turn_stopped
  
multiballs:
  3balls_multiball:
    ball_count: 3
    ball_count_type: total
    shoot_again: 0s
    start_events: logicblock_mb_counter_complete

counters:
  mb_counter:
    count_events: s_tward_active
    count_complete_value: 3
    reset_events: multiball_3balls_multiball_ended, ball_ended, player_turn_started
    
show_player:

  logicblock_mb_counter_complete:
    threshmb:
      priority: 900
      speed: 13
      loops: 0    
    threshmbsmall:
      priority: 900
      speed: 13
      loops: 0       
