#config_version=5
##! mode: match
# in modes/match/config/match.yaml
queue_relay_player:
  match_no_match:
    post: no_match
    wait_for: slide_no_match_slide_removed
    pass_args: true
  match_has_match:
    post: has_match
    wait_for: slide_match_slide_removed
    pass_args: true
mode_settings:
  non_match_number_step: 10
slide_player:
  no_match:
    no_match_slide:
      expire: 3s
  has_match:
    match_slide:
      expire: 3s
sound_player:
  match_no_match:
    no_match_sound:
      action: play
  match_has_match:
    match_sound:
      action: play
slides:
  match_slide:
    - type: text
      font_size: 30
      text: MATCH
    - type: text
      text: "Player 1: (match_number0)"
      font_size: 30
    - type: text
      text: "Player 2: (match_number1)"
      font_size: 30
    - type: text
      text: "Player 3: (match_number2)"
      font_size: 30
    - type: text
      text: "Player 4: (match_number3)"
      font_size: 30
    - type: text
      text: "Match number: (winner_number)"
      font_size: 30
  no_match_slide:
    - type: text
      text: NO MATCH
      font_size: 30
      anchor_y: bottom
    - type: text
      text: "Player 1: (match_number0)"
      font_size: 30
    - type: text
      text: "Player 2: (match_number1)"
      font_size: 30
    - type: text
      text: "Player 3: (match_number2)"
      font_size: 30
    - type: text
      text: "Player 4: (match_number3)"
      font_size: 30
    - type: text
      text: "Match number: (winner_number)"
      font_size: 30