#config_version=5


##! mode: left_ramp
mode:
  start_events: mode_skillshot_stopped
  stop_events:
    - left_ramp_success
    - ball_will_end
  priority: 600


show_player: 

  mode_left_ramp_started: 

    left_ramp_show: 
      priority: 900
      speed: 13



    